# Generated by Django 2.2.5 on 2019-09-27 01:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agreement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('percent', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('code', models.CharField(blank=True, max_length=20, null=True)),
                ('fisio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('time', models.TimeField()),
                ('value', models.DecimalField(decimal_places=2, max_digits=8)),
                ('status', models.CharField(blank=True, choices=[('Pendente', 'Pendente'), ('Faltou', 'Faltou'), ('Realizado', 'Realizado')], max_length=32, null=True)),
                ('fisio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Diagnostic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('day', models.DateField()),
                ('anamnese', models.CharField(blank=True, max_length=1024, null=True)),
                ('fowarding', models.CharField(blank=True, max_length=1024, null=True)),
                ('qp', models.CharField(blank=True, max_length=1024, null=True)),
                ('hma', models.CharField(blank=True, max_length=1024, null=True)),
                ('hmf', models.CharField(blank=True, max_length=1024, null=True)),
                ('hmp', models.CharField(blank=True, max_length=1024, null=True)),
                ('medication', models.CharField(blank=True, max_length=1024, null=True)),
                ('evolution', models.CharField(blank=True, max_length=512, null=True)),
                ('observation', models.CharField(blank=True, max_length=1024, null=True)),
                ('functional', models.CharField(blank=True, max_length=1024, null=True)),
                ('trainning', models.CharField(blank=True, max_length=1024, null=True)),
                ('physic_exam', models.CharField(blank=True, max_length=512, null=True)),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Appointment')),
                ('fisio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Procedure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('value', models.DecimalField(decimal_places=2, max_digits=8)),
                ('fisio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=556)),
                ('height', models.DecimalField(decimal_places=2, max_digits=3)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=4)),
                ('email', models.CharField(max_length=500)),
                ('celphone', models.CharField(max_length=13)),
                ('addres_1', models.CharField(max_length=322)),
                ('addres_2', models.CharField(max_length=322)),
                ('addres_3', models.CharField(max_length=322)),
                ('city', models.CharField(max_length=128)),
                ('state', models.CharField(max_length=48)),
                ('cpf', models.CharField(max_length=11)),
                ('rg', models.CharField(max_length=11)),
                ('born', models.DateField()),
                ('description', models.TextField()),
                ('agreement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.Agreement')),
                ('fisio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ImageProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.ImageField(upload_to='images/')),
                ('description', models.CharField(blank=True, max_length=512, null=True)),
                ('fisio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Patient')),
            ],
        ),
        migrations.CreateModel(
            name='ImageDiagnostic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.ImageField(upload_to='images/')),
                ('description', models.CharField(blank=True, max_length=512, null=True)),
                ('diagnostic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Diagnostic')),
                ('fisio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FieldDiagnostic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1024)),
                ('diagnostic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnostics', to='api.Diagnostic')),
                ('procedure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Procedure')),
            ],
        ),
        migrations.AddField(
            model_name='diagnostic',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Patient'),
        ),
        migrations.CreateModel(
            name='BillToRecieve',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, max_digits=8)),
                ('date', models.DateField()),
                ('fisio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Patient')),
            ],
        ),
        migrations.CreateModel(
            name='BillToPay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, max_digits=8)),
                ('date', models.DateField()),
                ('description', models.CharField(max_length=256)),
                ('fisio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='appointment',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.Patient'),
        ),
    ]
