# Generated by Django 2.2.2 on 2019-07-13 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_fielddiagnostic'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='status',
            field=models.CharField(blank=True, choices=[('Pendente', 'Pendente'), ('Faltou', 'Faltou'), ('Realizado', 'Realizado')], max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='diagnostic',
            name='anamnese',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='diagnostic',
            name='evolution',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='diagnostic',
            name='observation',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='diagnostic',
            name='physic_exam',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='diagnostic',
            name='scale',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='diagnostic',
            name='trainning',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
