# Generated by Django 2.2.5 on 2019-09-16 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20190713_1914'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diagnostic',
            old_name='scale',
            new_name='fowarding',
        ),
        migrations.AddField(
            model_name='diagnostic',
            name='functional',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='diagnostic',
            name='hma',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='diagnostic',
            name='hmf',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='diagnostic',
            name='hmp',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='diagnostic',
            name='medication',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='diagnostic',
            name='qp',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
